export { schedulesData };

const schedulesData = [
  {
    id: "kTMSq6018qGj",
    day: "Monday",
    startHour: "9:00 a.m.",
    endHour: "1:00 p.m.",
    tutor: {
      id: "wx-nWZPAX1TC",
      name: "Alin",
    },
    location: "https://www.youtube.com/watch?v=3imO7PFU5cI",
    isActive: false,
  },
  {
    id: "abMSq6018qGj",
    day: "Monday",
    startHour: "1:00 p.m.",
    endHour: "5:00 p.m.",
    tutor: { id: "2ZXHi4q7J_9m", name: "Andrew" },
    location: "https://www.youtube.com/watch?v=_v98All94pc",
    isActive: false,
  },
  {
    id: "kTMSq6018q78",
    day: "Tuesday",
    startHour: "10:00 a.m.",
    endHour: "1:00 p.m.",
    tutor: { id: "Zt5_isRtMR10", name: "Victor" },
    location: "Victor's Zoom link",
    isActive: false,
  },
  {
    id: "kTMSq6018123",
    day: "Tuesday",
    startHour: "11:00 a.m.",
    endHour: "3:00 p.m.",
    tutor: { id: "nWZPAX1TCdfg", name: "Alin" },
    location: "Alin's Zoom link",
    isActive: false,
  },
  {
    id: "kTMSq6011234",
    day: "Friday",
    startHour: "1:00 p.m.",
    endHour: "6:00 p.m.",
    tutor: { id: "2ZXHi4q7J_9m", name: "Andrew" },
    location: "Andrew's Zoom link",
    isActive: false,
  },
  {
    id: "1234q6018qGj",
    day: "Saturday",
    startHour: "10:00 a.m.",
    endHour: "3:00 p.m.",
    tutor: { id: "Zt5_isRtMR10", name: "Victor" },
    location: "Victor's Zoom link",
    isActive: false,
  },
];
